name: Deploy to rubygems.org
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Gem
        uses: cadwallion/publish-rubygems-action@v1.0.0
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_KEY }}
